# Generated by Django 3.0.5 on 2020-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
