# Generated by Django 3.0.5 on 2020-05-18 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_xp_to_lvlup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_to_lvlup',
            field=models.IntegerField(default=1515, validators=[django.core.validators.MinValueValidator(1515)]),
        ),
    ]
