# Generated by Django 3.0.5 on 2020-04-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200427_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='difficulty',
        ),
    ]
