# Generated by Django 3.0.5 on 2020-04-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200430_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authId',
            new_name='auth0_id',
        ),
    ]
