# Generated by Django 3.0.5 on 2020-04-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200430_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='auth0_id',
            new_name='auth0Id',
        ),
    ]
