# Generated by Django 3.0.5 on 2020-04-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200430_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
