# Generated by Django 3.0.5 on 2020-04-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200430_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.User'),
        ),
    ]
